# Generated by Django 5.0.1 on 2024-02-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='berth_day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
