# Generated by Django 5.0.1 on 2024-02-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_berth_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='berth_day',
        ),
    ]
