# Generated by Django 5.0.1 on 2024-03-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarview', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
