# Generated by Django 5.0.1 on 2024-02-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0003_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
