# Generated by Django 5.0.1 on 2024-03-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0005_schedulebarber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulebarber',
            name='time',
        ),
        migrations.AddField(
            model_name='schedulebarber',
            name='durations',
            field=models.DurationField(null=True),
        ),
    ]
