# Generated by Django 5.0.1 on 2024-03-02 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0007_alter_schedulebarber_durations'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='getting_started',
            field=models.TimeField(default=datetime.time(9, 0), null=True),
        ),
        migrations.AlterField(
            model_name='schedulebarber',
            name='durations',
            field=models.DurationField(default=32400, null=True),
        ),
    ]
