# Generated by Django 5.0.1 on 2024-03-02 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0008_barber_getting_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='end_of_work',
            field=models.TimeField(default=datetime.time(18, 0), null=True),
        ),
    ]
