# Generated by Django 5.0.1 on 2024-03-02 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0009_barber_end_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='end_of_work',
            field=models.TimeField(default=datetime.time(18, 0), null=True, verbose_name='Окончание работы'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='getting_started',
            field=models.TimeField(default=datetime.time(9, 0), null=True, verbose_name='Начало работы'),
        ),
    ]
