# Generated by Django 5.0.1 on 2024-03-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0010_alter_barber_end_of_work_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulebarber',
            name='durations',
        ),
    ]
