# Generated by Django 5.0.1 on 2024-03-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0012_alter_schedulebarber_barber'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulebarber',
            name='working',
            field=models.BooleanField(default=True, verbose_name='Работает да/нет'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='foto',
            field=models.ImageField(upload_to='Barber', verbose_name='Фото'),
        ),
    ]
