# Generated by Django 5.0.1 on 2024-03-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0013_schedulebarber_working_alter_barber_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barber',
            options={'ordering': ['name'], 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='schedulebarber',
            options={'ordering': ['day'], 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterField(
            model_name='schedulebarber',
            name='day',
            field=models.DateField(null=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='schedulebarber',
            name='working',
            field=models.BooleanField(default=False, verbose_name='Работает да/нет'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('price', models.FloatField()),
                ('durations', models.DurationField()),
                ('barber', models.ManyToManyField(to='barber.barber')),
            ],
        ),
    ]
