# Generated by Django 5.0.1 on 2024-03-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0014_alter_barber_options_alter_schedulebarber_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['name'], 'verbose_name_plural': 'Прайс лист'},
        ),
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
