# Generated by Django 5.0.1 on 2024-03-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0015_alter_price_options_alter_price_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='barber',
            field=models.ManyToManyField(to='barber.barber', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='price',
            name='durations',
            field=models.DurationField(verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.RemoveField(
            model_name='schedulebarber',
            name='barber',
        ),
        migrations.AddField(
            model_name='schedulebarber',
            name='barber',
            field=models.ManyToManyField(to='barber.barber', verbose_name='Мастер'),
        ),
    ]
