# Generated by Django 5.0.1 on 2024-03-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0017_remove_schedulebarber_barber_schedulebarber_barber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulebarber',
            name='barber',
        ),
        migrations.AddField(
            model_name='schedulebarber',
            name='barber',
            field=models.ManyToManyField(to='barber.barber', verbose_name='Мастер'),
        ),
    ]
