# Generated by Django 5.0.1 on 2024-03-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0018_remove_schedulebarber_barber_schedulebarber_barber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulebarber',
            name='working',
        ),
    ]
