# Generated by Django 5.0.1 on 2024-03-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0019_remove_schedulebarber_working'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('barber', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Клиенты',
                'ordering': ['time'],
            },
        ),
    ]
