# Generated by Django 5.0.1 on 2024-03-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0020_worklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklist',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='worklist',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
