# Generated by Django 5.0.1 on 2024-03-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0021_worklist_email_worklist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklist',
            name='email',
        ),
        migrations.AddField(
            model_name='worklist',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='worklist',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
