# Generated by Django 5.0.1 on 2024-02-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_barber_service_barber_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='service',
        ),
        migrations.AddField(
            model_name='barber',
            name='service',
            field=models.ManyToManyField(null=True, to='services.service'),
        ),
    ]
