# Generated by Django 5.0.1 on 2024-02-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_barber_service_barber_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='barber',
            field=models.ManyToManyField(to='services.barber'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
