# Generated by Django 5.0.1 on 2024-02-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_barber_service_service_barber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='work',
            field=models.BooleanField(default=True, verbose_name='Работает'),
        ),
        migrations.AddField(
            model_name='barber',
            name='work_date',
            field=models.DateField(default=False, verbose_name='Рабочий день'),
        ),
    ]
