# Generated by Django 5.0.1 on 2024-02-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_barber_work_barber_work_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='work_date',
            field=models.DateField(auto_now=True, verbose_name='Рабочий день'),
        ),
    ]
