# Generated by Django 5.0.1 on 2024-02-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_barber_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='work',
            field=models.BooleanField(null=True),
        ),
    ]
