# Generated by Django 5.0.1 on 2024-02-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_barber_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='work',
        ),
        migrations.RemoveField(
            model_name='barber',
            name='work_date',
        ),
    ]
