# Generated by Django 5.0.1 on 2024-02-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_remove_barber_work_remove_barber_work_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='barber',
        ),
        migrations.AddField(
            model_name='barber',
            name='service',
            field=models.ManyToManyField(to='services.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
